name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<your-ec2-instance-public-ip> << 'EOF'
          cd /path/to/your-repo
          git pull
          pip3 install -r requirements.txt
          pkill -f uvicorn || true
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        EOF
